const CONFIG = Object.freeze({
  TIMEZONE: 'America/Bogota',
  SCRIPT_PROPERTIES: {
    SPREADSHEET_ID: 'SPREADSHEET_ID',
    AUTH_FALLBACK: 'AUTH_FALLBACK',
    AUTH_TOKEN_SECRET: 'AUTH_TOKEN_SECRET'
  },
  SPREADSHEET_ID_FALLBACK: '',
  AUTH_FALLBACKS: {
    BLOCK_WRITES: 'BLOCK_WRITES',
    READ_ONLY: 'READ_ONLY',
    ALLOW_DEVELOPMENT: 'ALLOW_DEVELOPMENT'
  },
  SHEETS: {
    ACTIONS: 'Base',
    PARAMETERS: 'Parámetros',
    USERS: 'Usuarios',
    AUDIT: 'Historial'
  },
  ACTIONS_TITLE_ROW: 1,
  ACTIONS_HEADER_ROW: 2,
  ACTIONS_DATA_START_ROW: 3,
  ACTION_FIELDS: [
    'id',
    'fechaElaboracion',
    'origen',
    'tipoAccion',
    'proceso',
    'identificadoPor',
    'liderProceso',
    'descripcion',
    'equipoMejoramiento',
    'identificacionCausas',
    'causaRaiz',
    'correccion',
    'accion',
    'responsable',
    'fechaApertura',
    'fechaCierre',
    'fechaInicioAccion',
    'fechaFinAccion',
    'presupuesto',
    'revisionResponsable',
    'revisionFecha',
    'revisionObservacion',
    'validacionResponsable',
    'validacionFecha',
    'validacionObservacion',
    'evidencia',
    'auditorInterno',
    'fechaEvaluacion',
    'eficacia',
    'evaluacionObservacion',
    'estado',
    'equipoMejoramientoDetalle',
    'causasDefinitivas',
    'planMejoramiento',
    'estadoActual',
    'correoEnviado',
    'fechasBloqueadas',
    'accionContencion',
    'recomendacionesFinales'
  ],
  ACTIONS_COLUMNS: Object.freeze({
    id: 1,
    fechaElaboracion: 2,
    origen: 3,
    tipoAccion: 4,
    proceso: 5,
    identificadoPor: 6,
    liderProceso: 7,
    descripcion: 8,
    equipoMejoramiento: 9,
    identificacionCausas: 10,
    causaRaiz: 11,
    correccion: 12,
    accion: 13,
    responsable: 14,
    fechaApertura: 15,
    fechaCierre: 16,
    fechaInicioAccion: 17,
    fechaFinAccion: 18,
    presupuesto: 19,
    revisionResponsable: 20,
    revisionFecha: 21,
    revisionObservacion: 22,
    validacionResponsable: 23,
    validacionFecha: 24,
    validacionObservacion: 25,
    evidencia: 26,
    auditorInterno: 27,
    fechaEvaluacion: 28,
    eficacia: 29,
    evaluacionObservacion: 30,
    estado: 31,
    equipoMejoramientoDetalle: 32,
    causasDefinitivas: 33,
    planMejoramiento: 34,
    estadoActual: 35,
    correoEnviado: 36,
    fechasBloqueadas: 37,
    accionContencion: 38,
    recomendacionesFinales: 39
  }),
  ACTIONS_HEADERS: [
    'Numero de la accion',
    'Fecha de elaboracion',
    'Origen',
    'Tipo de accion',
    'Proceso/Subproceso',
    'Nombre de quien identifica la situacion',
    'Para: lider de proceso',
    'Descripcion',
    'Equipo de mejoramiento',
    'Identificacion de causas',
    'Causa raiz',
    'Correccion',
    'Accion',
    'Responsable',
    'Fecha de apertura',
    'Fecha de cierre',
    'Fecha inicio accion',
    'Fecha fin accion',
    'Presupuesto',
    'Responsable revision',
    'Fecha ejecucion revision',
    'Observacion revision',
    'Responsable validacion',
    'Fecha ejecucion validacion',
    'Observacion validacion',
    'Evidencia',
    'Auditor Interno',
    'Fecha de evaluacion',
    'Las acciones tomadas fueron EFICACES?',
    'Observacion',
    'ESTADO',
    'Detalle equipo de mejoramiento JSON',
    'Causas definitivas JSON',
    'Plan de mejoramiento JSON',
    'Estado_Actual',
    'correo_enviado',
    'fechas_bloqueadas',
    'Accion de contencion',
    'Recomendaciones finales'
  ],
  PARAMETER_COLUMNS: Object.freeze({
    origenes: 1,
    tiposAccion: 2,
    procesos: 3,
    personas: 4,
    lideresProceso: 5,
    relacionProcesoLider: 6,
    lideresSiplag: 7,
    auditores: 8
  }),
  PARAMETER_HEADERS: [
    'Origen',
    'Tipo de acciÃ³n',
    'Procesos',
    'Nombre de quien identifica la situaciÃ³n',
    'LÃ­deres de procesos',
    'RelaciÃ³n proceso y lÃ­der',
    'Responsables de revisiÃ³n o lÃ­deres SIPLAG',
    'Auditores internos'
  ],
  USERS_HEADERS: ['email', 'nombre', 'proceso', 'rol', 'password_salt', 'password_hash', 'activo'],
  AUDIT_HEADERS: [
    'timestamp',
    'usuario',
    'operacion',
    'accionId',
    'fila',
    'datosAnterioresJson',
    'datosNuevosJson'
  ],
  ROLES: {
    ADMIN: ['read', 'create', 'update', 'admin', 'phase:registro', 'phase:analisis', 'phase:plan', 'phase:validacion', 'phase:oci', 'notify:oci'],
    CREADOR: ['read', 'create', 'update', 'phase:registro', 'phase:analisis'],
    REV: ['read', 'create', 'update', 'phase:registro', 'phase:analisis', 'phase:plan', 'notify:oci'],
    VAL: ['read', 'create', 'update', 'phase:registro', 'phase:analisis', 'phase:validacion'],
    OCI: ['read', 'create', 'update', 'phase:registro', 'phase:analisis', 'phase:oci'],
    CONSULTA: ['read']
  },
  EFFECTIVENESS_VALUES: ['SI', 'NO', ''],
  STATUS_RULE: {
    OPEN_WHEN_EFFECTIVENESS_EMPTY: 'ABIERTA',
    CLOSED_WHEN_EFFECTIVENESS_PRESENT: 'CERRADA'
  },
  INITIAL_PROCESSES: [
    ['GG', 'GestiÃ³n Gerencial'],
    ['PE', 'PlaneaciÃ³n EstratÃ©gica'],
    ['GC', 'GestiÃ³n de Comunicaciones'],
    ['GJ', 'GestiÃ³n JurÃ­dica'],
    ['GSI', 'GestiÃ³n de Sistemas de InformaciÃ³n'],
    ['SIPLAG', 'Sistema Integrado de PlaneaciÃ³n y GestiÃ³n'],
    ['GCR', 'GestiÃ³n del Conocimiento del Riesgo'],
    ['GRR', 'GestiÃ³n de ReducciÃ³n del Riesgo'],
    ['GMD', 'GestiÃ³n de Manejo de Desastres'],
    ['GTH', 'GestiÃ³n del Talento Humano'],
    ['GF', 'GestiÃ³n Financiera'],
    ['GCT', 'GestiÃ³n de ContrataciÃ³n'],
    ['CD', 'Control Disciplinario'],
    ['GCI', 'GestiÃ³n de CooperaciÃ³n Internacional'],
    ['GA', 'GestiÃ³n Administrativa'],
    ['SSA', 'Servicios Administrativos'],
    ['SGD', 'GestiÃ³n Documental'],
    ['SGSC', 'Servicio al Ciudadano'],
    ['SIT', 'Infraestructura TecnolÃ³gica'],
    ['GBMI', 'GestiÃ³n de Bienes Muebles e Inmuebles'],
    ['ES', 'EvaluaciÃ³n y Seguimiento'],
    ['OTRO', 'Otro proceso']
  ]
});
